name: 📋 draft release

run-name: 📋 @${{ github.triggering_actor }} is drafting a release

on:
  push:
    branches: [ main ]

jobs:
  draft-release:
    name: 📋 draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: asdf-vm/actions/install@v3
      - run: npm clean-install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
