name: 🔬 quality checks

run-name: 🔬 @${{ github.triggering_actor }} is checking quality on ${{ github.ref_name }}

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: 🧹 lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: make init
      - run: make lint

  test-with-coverage:
    name: 🧪 test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: make init
      - run: make test/coverage/report
      - run: curl https://deepsource.io/cli | sh
      - name: deepsource report
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          ./bin/deepsource report \
            --analyzer test-coverage \
            --key javascript \
            --value-file "$(realpath ./coverage/lcov.info)"
